version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    networks:
      - custom

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.167.60.0/16